name: forkobo_merchant
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.3.0
  easy_localization: ^3.0.7
  timezone: ^0.10.0
  flutter_native_splash: ^2.4.4
  overlay_support: ^2.1.0
  go_router: ^15.1.2
  dio: ^5.7.0
  get_it: ^8.0.3
  logger: ^2.5.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.3.1
  shared_preferences: ^2.3.5
  gap: ^3.0.1
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_platform_alert: ^0.6.1
  fl_chart: ^0.66.0

 #####
  # dw_image_picker: ^1.2.17
  # photo_view: ^0.15.0
  modal_bottom_sheet: ^3.0.0
  url_launcher: ^6.3.1
  flutter_spinkit: ^5.2.1
  random_avatar: ^0.0.8
  webview_flutter: ^4.10.0
  timeago: ^3.7.1
  hexcolor: ^3.0.1
  flutter_vibrate:
    git:
      url: https://github.com/saytoonz/flutter_vibrate.git
      ref: android-upgrade-and-java_to_kotlin
  shorebird_code_push: ^2.0.4
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.2.7
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  # flutter_signin_button: ^2.0.0
  package_info_plus: ^8.3.0
  firebase_remote_config: ^5.5.0
  phone_numbers_parser: ^9.0.3
  family_bottom_sheet: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/logo-mark.png
  fullscreen: true
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/jpeg/
    - assets/icon/
    - assets/lottie/
    - assets/translations/
    # - shorebird.yaml
  
  fonts:
    - family: PlayWriteHU
      fonts:
        - asset:  assets/fonts/PlaywriteHU-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
